### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by FrantzCFelix** [FrantzCFelix/RINQYDINK#26]
_http_outgoing.js:482
    throw new ERR_HTTP_HEADERS_SENT('set');
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:482:11)
    at ServerResponse.header (C:\Users\frant\Documents\uw-coding-bootcamp-desktop\RINQYDINK\node_modules\express\lib\response.js:771:10)
    at ServerResponse.send (C:\Users\frant\Documents\uw-coding-bootcamp-desktop\RINQYDINK\node_modules\express\lib\response.js:170:12)
    at done (C:\Users\frant\Documents\uw-coding-bootcamp-desktop\RINQYDINK\node_modules\express\lib\response.js:1008:10)
    at Immediate.<anonymous> (C:\Users\frant\Documents\uw-coding-bootcamp-desktop\RINQYDINK\node_modules\express-handlebars\lib\utils.js:26:13)
    at processImmediate (timers.js:632:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rinqydink@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rinqydink@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\frant\AppData\Roaming\npm-cache\_logs\2020-03-11T04_04_57_073Z-debug.log

**Comment by ddhoang21** [comment]
solved
